[package]
name = "adventOfCode2018"
version = "0.1.0"
authors = ["benWindsorCode <benjaminwindsor@hotmail.co.uk>"]
edition = "2018"

[[bin]]
name = "day_one"
path = "src/day_one.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
